# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'

- script: |
    pip install bandit
    bandit -r . -f json -o bandit-result.json | echo 'true'
  displayName: 'Run bandit analysis'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud_fffdsi'
    organization: 'fffdsi'
    scannerMode: 'CLI'
    configMode: 'file'
    configFile: 'backend/sonar-project.properties'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'